services:

    redpanda:
        image: docker.redpanda.com/redpandadata/console
        hostname: redpanda
        container_name: correos-redpanda
        ports:
            - "8080:8080"
        environment:
            KAFKA_BROKERS: kafka:29092
            KAFKA_TLS_INSECURESKIPTLSVERIFY: true
            KAFKA_SCHEMAREGISTRY_ENABLED: true
            KAFKA_SCHEMAREGISTRY_URLS: http://schema-registry:8081
            KAFKA_SCHEMAREGISTRY_USERNAME: client
            KAFKA_SCHEMAREGISTRY_PASSWORD: client
            KAFKA_SCHEMAREGISTRY_TLS_ENABLED: false
            KAFKA_SCHEMAREGISTRY_TLS_INSECURESKIPTLSVERIFY: true
        depends_on:
            - kafka
            - schema-registry
            - zookeeper
        restart: always

    zookeeper:
        image: confluentinc/cp-zookeeper:6.1.1
        hostname: zookeeper
        container_name: correos-zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        restart: always

    kafka:
        image: confluentinc/cp-enterprise-kafka:6.1.1
        hostname: kafka
        container_name: correos-kafka
        tmpfs: /kafka/kafka-logs
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_HEAP_OPTS: -Xmx3G -Xms1G
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_DELETE_TOPIC_ENABLE: "true"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_LOG_RETENTION_MS: -1
            KAFKA_MESSAGE_MAX_BYTES: 10485880
            KAFKA_NUM_PARTITIONS: 1
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:9092
            CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
            CONFLUENT_METRICS_ENABLE: "true"
            CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always

    schema-registry:
        image: confluentinc/cp-schema-registry:6.1.1
        container_name: correos-schema-registry
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
            SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
            SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: NONE
        depends_on:
            - kafka
        restart: always

    redis-packages:
        container_name: correos-redis-packages
        image: redis:7.4.1-alpine3.20
        ports:
            - "6379:6379"
        volumes:
            - redis-packages-data:/data
        environment:
            - REDIS_DATABASE=0
    redis-riders:
        container_name: correos-redis-riders
        image: redis:7.4.1-alpine3.20
        ports:
            - "6380:6379"
        volumes:
            - redis-riders-data:/data
        environment:
            - REDIS_DATABASE=1
    redis-last-topic:
        container_name: correos-redis-last-topic
        image: redis:7.4.1-alpine3.20
        ports:
            - "6381:6379"
        volumes:
            - redis-last-topic-data:/data
        environment:
            - REDIS_DATABASE=2


networks:
    default:
        name: correos

volumes:
    redis-packages-data:
    redis-riders-data:
    redis-last-topic-data: