server.port: 8004

topic-in-0: package-and-rider
topic-out-0: package-history

spring:
    application.name: agr-package-history
    cloud:
        function.definition: aggregatePackageHistory;
        stream:
            bindings:
                aggregatePackageHistory-in-0:
                    destination: ${topic-in-0}
                    consumer:
                        concurrency: 1
                        useNativeDecoding: true
                aggregatePackageHistory-out-0:
                    destination: ${topic-out-0}
                    producer.useNativeEncoding: true
            kafka:
                binder:
                    brokers: localhost:9092
            kafka.streams:
                bindings:
                    aggregatePackageHistory-in-0:
                        consumer:
                            keySerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                            valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                            applicationId: ${spring.application.name}
                binder:
                    configuration:
                        commit.interval.ms: 100
                        session.timeout.ms: 10000
                        schema.registry.url: http://localhost:8081
                        auto.register.schemas: true
                        default.key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
                        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde